### PR TITLE
Scaffold sample data + list and item components

### PR DESCRIPTION
**Pull request by jacobarriola**
This PR scaffolds the `todo-list` and `todo-items` components for the application. No functionality is present at this moment.

Additionally, sample data is added via a temporary module, which will eventually be replaced by a backend service.

### CODE REVIEW

**Comment by moltenkaizen** [comment]
Looks great to me but what about the ideas of archiving tasks? Do we need an archived property or do we want to just keep another array of deleted/archived tasks once they are deleted? Or perhaps we add that later. I'm also thinking we'll need some tabs or other way of toggling between active, completed, and archived tasks.

**Comment by angelocordon** [comment]
@jacobarriola - nitpicking, but sharing some professional conventions from work - 

We usually keep file names in lowercase and underscore. So things like `Todo-Item.vue` should be `todo_item.vue`. I think this follows unix convention as well.

Also - I like how we can compose individual components - but not sure if I like having all parts of the component in one file - the template, the script and the style. Leaning to you here - is there a better convention to follow? I guess that would be the advantage of having a vue file? Instead of:

```
components/todo_item/
  |_ template.js
  |_ todo_item.js
  |_ todo_item.scss
```

Thoughts?

**Comment by angelocordon** [comment]
Also, last comment - are you using two tab spaces? Let's do one - not sure if that's a setting between our editors.

**Comment by jacobarriola** [comment]
Interesting with the naming convention. Looking around different vue projects, seems like `.vue` files are capitalized, especially true if we look at the provided `App.vue` via cli. Nothing official, but prob best to stick with what the community is sticking to.

Having the `<template>`, `<script>`, and `<style>` inside the `.vue` file is one of the major advantages of the loader, especially how you can scope your CSS to the one component. Takes modularity to another level.

I prob have tabs set up to 4. I'll adjust it.

**Comment by moltenkaizen** [comment]
Hey guys, in the examples I've seen the components are named like `NiceComponent.vue`
Here's an official example in the Vue repo [vue-hackernews
](https://github.com/vuejs/vue-hackernews/tree/gh-pages/src/components)

Ok so we're agreeing to use 2 spaces to indent.

No comments on my question about handing task.archived or a separate archived array? Please let me know how this should work. Are those things to be decided later? Thanks

**Comment by jacobarriola** [comment]
@moltenkaizen that's a good point with regards to the archived or 'done' tasks. Nothing comes to mind right away with how to handle that 🤔 

Maybe it's a two-step process: one step completes the task, and a second step archives it.

**Comment by jacobarriola** [comment]
@moltenkaizen @angelocordon this ok to merge in to `master`? It's some basic scaffolding, so I think we're in the clear. I changed the formatting to from 4 to 2, so I think we're good.

**Comment by angelocordon** [comment]
🔥 great work @jacobarriola

**Comment by jacobarriola** [comment]
Sweet!

**Pull request merged**
